server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 7292
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
